Revert "bring back fixed exposed ports"
This reverts commit 1edf4f0d5473027f645a6075e1a6e1fc72713149.

We cannot use fixed ports for the app, because that prevents scaling:

```
% docker-compose scale app=2
WARNING: The "app" service specifies a port on the host. If multiple
containers for this service are created on a single host, the port will
clash.
Creating and starting monitoringworkshop_app_2 ... error

ERROR: for monitoringworkshop_app_2  driver failed programming external
connectivity on endpoint monitoringworkshop_app_2
(c0b9dac144d417bc27c7d8f0ca7d293fc04c04a63b639354ba1bc54b9af82622): Bind
for 0.0.0.0:8080 failed: port is already allocated
```